# Generated by Django 2.0.4 on 2018-04-08 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='propertie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('bedroom', models.IntegerField(default=0)),
                ('bathroom', models.IntegerField(default=0)),
                ('zipcode', models.CharField(max_length=5)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('square_feet', models.IntegerField(default=0)),
                ('unit', models.CharField(max_length=20)),
                ('rent', models.BooleanField(default=False)),
                ('description', models.CharField(max_length=200)),
                ('longitude', models.FloatField(default=0)),
                ('latitude', models.FloatField(default=0)),
                ('user_id', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('home_type_id', models.IntegerField(default=0)),
                ('rooms', models.IntegerField(default=0)),
                ('contact_number', models.CharField(max_length=50)),
            ],
        ),
    ]
