# Generated by Django 2.0.4 on 2018-04-08 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_auto_20180408_2120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertie',
            name='rent',
        ),
        migrations.AddField(
            model_name='propertie',
            name='property_type',
            field=models.CharField(choices=[('S', 'Sale'), ('R', 'Rent')], default='S', max_length=1),
        ),
    ]
